disabled_rules: # rule identifiers to exclude from running
  # - closing_brace
  # - colon
  - comma
  - control_statement
  - custom_rules
  - cyclomatic_complexity
  - discarded_notification_center_observer
  - empty_count
  - empty_parentheses_with_trailing_closure
  - file_length
  - force_cast
  - force_try
  - force_unwrapping
  - for_where
  - function_body_length
  - function_parameter_count
  - leading_whitespace
  - legacy_constant
  - legacy_constructor
  - line_length
  # - mark
  - missing_docs
  - multiple_closures_with_trailing_closure
  - nesting
  # - opening_brace
  - operator_whitespace
  - return_arrow_whitespace
  - redundant_discardable_let
  - redundant_optional_initialization
  # - redundant_void_return
  - statement_position
  - shorthand_operator
  - todo
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - identifier_name
  # - vertical_whitespace
  # - void_return
  - unused_closure_parameter
  - unneeded_break_in_switch
  - unused_optional_binding
  - private_over_fileprivate
  - weak_delegate
excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
opt_in_rules: # some rules are only opt-in
  - empty_count
  - vertical_whitespace_closing_braces
cyclomatic_complexity:
  ignores_case_statements: true
  warning: 20
file_length:
  warning: 800
  error: 1000
line_length: 
  warning: 180 
  error: 350
  ignores_comments: true
  ignores_urls: true
nesting:
  type_level:
    warning: 3
    error: 6
  statement_level:
    warning: 5
    error: 10
colon: 
  severity: error
comma: error
empty_count: error
legacy_constant: error
legacy_constructor: error
opening_brace: error
trailing_newline: error
trailing_semicolon: error
opening_brace: error
closing_brace: error
